apiVersion: apps/v1
kind: Deployment
metadata:
  name: quorum
  namespace: quorum
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: quorum
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
