apiVersion: apps/v1
kind: Deployment
metadata:
  name: quorum
  namespace: quorum-staging
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: quorum
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
