DROP VIEW gl_reconcile_ar;
DROP TRIGGER trg_gl_waive ON dues_invoices;
DROP TRIGGER trg_gl_payment ON transactions;
DROP TRIGGER trg_gl_invoice ON dues_invoices;
DROP FUNCTION gl_post_waive();
DROP FUNCTION gl_invoice_remaining(UUID);
DROP FUNCTION gl_post_payment();
DROP FUNCTION gl_payment_credit_account(UUID, TEXT);
DROP FUNCTION gl_post_invoice();
DROP FUNCTION gl_post(DATE, TEXT, TEXT, UUID, UUID, UUID, BIGINT, TEXT);
DROP FUNCTION gl_cash_account(TEXT);
DROP FUNCTION gl_account(TEXT);
DROP TRIGGER trg_journal_balance ON journal_lines;
DROP FUNCTION journal_balance_check();
DROP TRIGGER trg_journal_lines_guard ON journal_lines;
DROP TRIGGER trg_journal_entries_guard ON journal_entries;
DROP FUNCTION journal_guard();
DROP TABLE journal_lines;
DROP TABLE journal_entries;
DROP TABLE accounts;
