{{- if not .Values.secrets.existingSecret }}
# Created only when existingSecret is not set.
# In production use existingSecret with Sealed Secrets or ESO instead.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quorum.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quorum.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep   # prevent accidental deletion on upgrade
type: Opaque
stringData:
  QUORUM_DATABASE_URL:           {{ .Values.secrets.databaseUrl | quote }}
  QUORUM_JWT_SECRET:             {{ .Values.secrets.jwtSecret | quote }}
  QUORUM_SMTP_PASS:              {{ .Values.secrets.smtpPass | quote }}
  QUORUM_STRIPE_WEBHOOK_SECRET:  {{ .Values.secrets.stripeWebhookSecret | quote }}
  QUORUM_PAYPAL_WEBHOOK_ID:      {{ .Values.secrets.paypalWebhookId | quote }}
{{- end }}
